<p>Pentru a folosi modulul, vă rugăm să introduceți datele de autentificare în pagina de configurare.</p><br />
<p>Nu aveți cont sendSMS?<br />
    Înregistrați-vă GRATUIT <a href="http://www.sendsms.ro/ro" target="_blank">aici</a>.<br />
    Mai multe detalii despre sendSMS puteți afla <a href="http://www.sendsms.ro/ro">aici</a>.</p>
<p>În pagina de setări, sub datele de autentificare, veți găsi câte un câmp text pentru fiecare status disponibil în WooCommerce. Va trebui să introduceți un mesaj pentru câmpurile la care doriți să se trimită sms de înștiințare. Dacă un câmp va fi gol, atunci sms-ul nu se va trimite.</p>
<p>Dacă doriți să trimiteți un mesaj când se schimbă statusul comenzii în finalizată (Completed) atunci va trebui să completați un mesaj în câmpul text <strong>"Mesaj: Completed"</strong>.</p><br />
<p>Puteți introduce variabile care se vor completa în funcție de datele de comandă.</p>
<p>Exemplu mesaj: <strong>Salut {billing_first_name}. Comanda ta cu numarul {order_number} a fost finalizata.</strong></p>
<p>Mesajul introdus nu trebuie să conțină diacritice. Dacă acestea sunt introduse literele cu diacritice vor fi înlocuite cu echivalentul lor fără diacritice.</p>
